//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.FAQPlusPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.FAQPlusPlus.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is what I found : {0}.
        /// </summary>
        public static string AnswerLineText {
            get {
                return ResourceManager.GetString("AnswerLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask An Expert.
        /// </summary>
        public static string AskAnExpertButtonText {
            get {
                return ResourceManager.GetString("AskAnExpertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always ask me to connect to an expert, an expert will connect with you:\n Ask an Expert..
        /// </summary>
        public static string AskAnExpertFunctionText {
            get {
                return ResourceManager.GetString("AskAnExpertFunctionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your detailed question and supporting details here..
        /// </summary>
        public static string AskAnExpertPlaceholderText {
            get {
                return ResourceManager.GetString("AskAnExpertPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask An Expert.
        /// </summary>
        public static string AskAnExpertText1 {
            get {
                return ResourceManager.GetString("AskAnExpertText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have our experts to assist you better  on any of your questions. You can always connect to our Experts..
        /// </summary>
        public static string AskAnExpertText2 {
            get {
                return ResourceManager.GetString("AskAnExpertText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string AssignStatusText {
            get {
                return ResourceManager.GetString("AssignStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Bot.
        /// </summary>
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 401k\r- Travel Benifits\r-  Leave Policy\r- Health Benifits.
        /// </summary>
        public static string BulletedList {
            get {
                return ResourceManager.GetString("BulletedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - May I know my 401k policy?\n- May I know the Travel Policy of the org?\n-  What about the Leave Policy?\n- What are the Health benefits?.
        /// </summary>
        public static string BulletedQuestionText {
            get {
                return ResourceManager.GetString("BulletedQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Chat Requested User is {0} :.
        /// </summary>
        public static string ChatWithRequestor {
            get {
                return ResourceManager.GetString("ChatWithRequestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseStatusText {
            get {
                return ResourceManager.GetString("CloseStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer the questions suggesting how we can improve our services or just leave the comments..
        /// </summary>
        public static string CollectFeedback {
            get {
                return ResourceManager.GetString("CollectFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Completed Date is {0} :.
        /// </summary>
        public static string CompletedDate {
            get {
                return ResourceManager.GetString("CompletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Question has been posted to our expert team.Someone from the team will get back to you in some time..
        /// </summary>
        public static string ConfirmationAdaptiveCardContent {
            get {
                return ResourceManager.GetString("ConfirmationAdaptiveCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation!.
        /// </summary>
        public static string ConfirmationCardTitleText {
            get {
                return ResourceManager.GetString("ConfirmationCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Created Date is {0}:.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t find anything. Do you want me to ask an expert..
        /// </summary>
        public static string CustomMessage {
            get {
                return ResourceManager.GetString("CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string EmailPlaceholderText {
            get {
                return ResourceManager.GetString("EmailPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your detailed feedback and supporting details here..
        /// </summary>
        public static string FeedbackDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("FeedbackDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackHeaderText {
            get {
                return ResourceManager.GetString("FeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would love to hear a feedback from you on how we have performed today..
        /// </summary>
        public static string FeedbackText1 {
            get {
                return ResourceManager.GetString("FeedbackText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your experience is unhappy give us the details you have for your question,like your assigned ticket #, one of our experts will connect with you..
        /// </summary>
        public static string FeedbackText2 {
            get {
                return ResourceManager.GetString("FeedbackText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask A Question!.
        /// </summary>
        public static string FunctionCardText1 {
            get {
                return ResourceManager.GetString("FunctionCardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am your QnA bot, you can ask me a question and I will answer you back if I know the answer..
        /// </summary>
        public static string FunctionCardText2 {
            get {
                return ResourceManager.GetString("FunctionCardText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me questions  like:.
        /// </summary>
        public static string FunctionTopicsText {
            get {
                return ResourceManager.GetString("FunctionTopicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: {0}.
        /// </summary>
        public static string IncomingAppFeedbackDetailsText {
            get {
                return ResourceManager.GetString("IncomingAppFeedbackDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: {0}.
        /// </summary>
        public static string IncomingAppFeedbackSubjectLine {
            get {
                return ResourceManager.GetString("IncomingAppFeedbackSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Expert Cardheader is {0} :.
        /// </summary>
        public static string IncomingAskAnExpertSMECardHeader {
            get {
                return ResourceManager.GetString("IncomingAskAnExpertSMECardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Feedback Cardheader is {0} :.
        /// </summary>
        public static string IncomingFeedbackSMECardHeader {
            get {
                return ResourceManager.GetString("IncomingFeedbackSMECardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shares {1}. The details are as follows:.
        /// </summary>
        public static string IncomingFeedbackSubHeaderText {
            get {
                return ResourceManager.GetString("IncomingFeedbackSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following are your last 10 requests:.
        /// </summary>
        public static string LastTenRequestsText {
            get {
                return ResourceManager.GetString("LastTenRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is what I can help you with:.
        /// </summary>
        public static string MessageText1 {
            get {
                return ResourceManager.GetString("MessageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are curious about what I can do, just type @FAQBot and I will present the list of commands that I can understand..
        /// </summary>
        public static string MessageText2 {
            get {
                return ResourceManager.GetString("MessageText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string NamePlaceholderText {
            get {
                return ResourceManager.GetString("NamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assigned value is.
        /// </summary>
        public static string NotAssigned {
            get {
                return ResourceManager.GetString("NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenStatusText {
            get {
                return ResourceManager.GetString("OpenStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has asked a question, it&apos;s important to take a look at their inquiry!.
        /// </summary>
        public static string QuestionForExpertSubHeaderText {
            get {
                return ResourceManager.GetString("QuestionForExpertSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request : {0}.
        /// </summary>
        public static string QuestionLineText {
            get {
                return ResourceManager.GetString("QuestionLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Id Text is {0} :.
        /// </summary>
        public static string RequestIdText {
            get {
                return ResourceManager.GetString("RequestIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request #.
        /// </summary>
        public static string RequestText {
            get {
                return ResourceManager.GetString("RequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ResultAnswerText {
            get {
                return ResourceManager.GetString("ResultAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question: {0}.
        /// </summary>
        public static string ResultQuestionText {
            get {
                return ResourceManager.GetString("ResultQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Feedback for above Result.
        /// </summary>
        public static string Resultsfeedbackdetails {
            get {
                return ResourceManager.GetString("Resultsfeedbackdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Feedback.
        /// </summary>
        public static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendDisplayText {
            get {
                return ResourceManager.GetString("SendDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App Feedback.
        /// </summary>
        public static string ShareAppFeedbackButtonText {
            get {
                return ResourceManager.GetString("ShareAppFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Feedback.
        /// </summary>
        public static string ShareFeedbackTitleText {
            get {
                return ResourceManager.GetString("ShareFeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusShowCardHeader {
            get {
                return ResourceManager.GetString("StatusShowCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Tour.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an SME, you can initiate chat directly with the end user, by clicking on chat button..
        /// </summary>
        public static string TeamChatCardContent {
            get {
                return ResourceManager.GetString("TeamChatCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate Chat with Users.
        /// </summary>
        public static string TeamChatHeaderText {
            get {
                return ResourceManager.GetString("TeamChatHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi SME Team, you are supposed to take questions from the user. If you want to ask me a question, please install me in your personal scope.To know better about me please  do Team Tour..
        /// </summary>
        public static string TeamCustomMessage {
            get {
                return ResourceManager.GetString("TeamCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SME channel receives feedback  from the users on the app performance or can ask a question  to the SME channel..
        /// </summary>
        public static string TeamFunctionCardContent {
            get {
                return ResourceManager.GetString("TeamFunctionCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from the Users.
        /// </summary>
        public static string TeamFunctionCardHeaderText {
            get {
                return ResourceManager.GetString("TeamFunctionCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Keep track of the user requests using the status assigned or closed..
        /// </summary>
        public static string TeamQueryCardContent {
            get {
                return ResourceManager.GetString("TeamQueryCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket System.
        /// </summary>
        public static string TeamQueryHeaderText {
            get {
                return ResourceManager.GetString("TeamQueryHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback has been captured and forwarded over to the team. Someone will get back to you in some time..
        /// </summary>
        public static string ThankYouAdaptiveCardContent {
            get {
                return ResourceManager.GetString("ThankYouAdaptiveCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string ThankYouAdaptiveCardTitleText {
            get {
                return ResourceManager.GetString("ThankYouAdaptiveCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I am {0}, thank you for having me in your SME team!.I am a  friendly HR bot can be used by  any team or individual within the org. As an SME, you and your team memebers can do following things using bot.\n- Can Self assign the tickets raised by the users.\n- Can directly chat with end user using chat buttons.\n- Your team can keep track of all the user queries using staus fields like open assign and close.,.
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} !.
        /// </summary>
        public static string WelcomeTeamCardTitleText {
            get {
                return ResourceManager.GetString("WelcomeTeamCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there!.
        /// </summary>
        public static string WelcomeText1 {
            get {
                return ResourceManager.GetString("WelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!   \nI am Sophia I am your friendly HR BOT. I am here to help you with your HR realted topics..
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
    }
}
